#!/bin/bash -v

set -e

cd `dirname $0`
thisdir=`pwd`
cd ..
basedir=`pwd`
cd $thisdir

insdir=$basedir/insdir

if [ dynmethoffs.exe -ot dynmethoffs.cs ]
then
    export PATH=$insdir/bin:$PATH
    mcs -debug -out:dynmethoffs.exe dynmethoffs.cs -reference:Mono.Tasklets.dll
fi

export MONO_PATH=$insdir/lib/mono/4.5
echo '=   =   =   ='
../mono/mini/mono-boehm --debug dynmethoffs.exe
echo '=  =  =  =  ='
../mono/mini/mono-sgen --debug dynmethoffs.exe
echo '= = = = = = ='

